name: 'CACE'
description: 'Composite action to run a CACE design'

inputs:
  volare_rev:
    description: 'Volare commit hash'
    required: false
    default: 'main'
  pdk_family:
    description: 'PDK family supported by volare, such as sky130'
    required: false
    default: 'sky130'
  open_pdks_rev:
    description: 'PDK hash for volare'
    required: false
    default: '823ec23c421cfb1d6aec06b8140cbde11cbc95a0'
  cace_rev:
    description: 'CACE commit hash'
    required: false
    default: 'main'
  cace_root:
    description: 'working directory'
    required: false
    default: '.'
  cace_datasheet:
    description: 'path to the datasheet relative to cace_root'
    required: false
    default: ''
  cace_source:
    description: 'source for the netlist [schematic, layout, rcx, all, best]'
    required: false
    default: 'best'
  cace_args:
    description: 'additional arguments for CACE'
    required: false
    default: ''
  token:
    description: 'Github PAT'
    required: true
runs:
  using: "composite"
  steps:

    # Install Nix
    - name: Install Nix
      uses: cachix/install-nix-action@v27
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ inputs.token }}

    # Setup the binary cache
    - name: Setup cache
      uses: cachix/cachix-action@v14
      with:
        name: openlane
        extraPullNames: openlane

    # Install the PDK from cache if available
    - name: Cache ${{ inputs.pdk_family }} PDK
      uses: actions/cache@v3
      with:
        path: ${{ github.workspace }}/.volare-${{ inputs.pdk_family }}
        key: cache-${{ inputs.pdk_family }}-pdk-${{ inputs.open_pdks_rev }}

    # Install PDK using volare
    - name: Enable ${{ inputs.pdk_family }} PDK
      uses: workflow/nix-shell-action@v3.3.2
      with:
        flakes: github:efabless/volare/${{ inputs.volare_rev }}
        script: |
          volare enable --pdk ${{ inputs.pdk_family }} --pdk-root ${{ github.workspace }}/.volare-${{ inputs.pdk_family }} ${{ inputs.open_pdks_rev }}
          echo "PDK_ROOT=${{ github.workspace }}/.volare-${{ inputs.pdk_family }}" >> $GITHUB_ENV

    # Run CACE
    - name: Run CACE
      uses: workflow/nix-shell-action@v3.3.2
      with:
        flakes: github:efabless/cace/${{ inputs.cace_rev }}
        script: |
          # Run CACE inside CACE_ROOT
          cd ${{ github.workspace }}
          cd ${{ inputs.cace_root }}
          cace ${{ inputs.cace_datasheet }} --source ${{ inputs.cace_source }} ${{ inputs.cace_args }}
